name: Terraform Resource deploying Pipeline
run-name: ${{ github.actor }} is working on pipeline

"on":
  push:
    branches:
      - main
  workflow_dispatch: 

  
jobs:
  terraform-job:
    name: 'terraform-plan'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    
    # Checkout Github Repo on Runner
      - name: Checkout Code from Github
        uses: actions/checkout@v2
    
    # Setup Terraform on Runner
      - name: Terraform Install
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init 
        run: terraform init
        
    

